### ISSUE TITLE
Provide a function that returns the last unlocked achievement for a game

### ISSUE THREAD

**Issue by oxisto** [aybaze/MetaAchiever#4]
Should be very similar to #1, should return the achievement "object" which was earned last, i.e. with the highest unlocktime property.

**Comment by ipecxx** [comment]
Is this still relevant to exist in a separate function @oxisto ? Alternative would be to extend the data model of Player to contain the last achieved Achievement. Can't tell about performance, however

**Comment by oxisto** [comment]
I think we can close this for now. We will probably do this later with Cypher queries.

On 12. Apr 2018, at 15:01, Andreas <notifications@github.com<mailto:notifications@github.com>> wrote:


Is this still relevant to exist in a separate function? Alternative would be to extend the data model of Player to contain the last achieved Achievement. Can't tell about performance, however
